/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.hr_scaffold.hr.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.hr_scaffold.hr.models.query.*;

public interface HRQueryExecutorService {

    Page<EmployeesByDepartmentResponse> executeEmployeesByDepartment(String deptid, Pageable pageable);

    Downloadable exportEmployeesByDepartment(ExportType exportType, String deptid, Pageable pageable);

    GetRegionResponse executeGetRegion(String username);

    Page<EmployeesByRegionResponse> executeEmployeesByRegion(Integer regionid, Pageable pageable);

    Downloadable exportEmployeesByRegion(ExportType exportType, Integer regionid, Pageable pageable);

}


