/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/


package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface HrdbQueryExecutorService {
    Page<Object> executeEmployeeListOf_DeptId1(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeEmployeeListOf_DeptId2(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeSrv_Var_EmployeeCount(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeTotalBudget(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeChecking(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeEmploteeList(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeEmployeeListOf_DeptId5(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeEmployeeListOf_DeptId4(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeSearchEmployees(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeNoOfDepartment(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeSelectEmployeeVar(Pageable pageable, java.lang.Integer SearchID, java.lang.Integer LiveListID) throws QueryParameterMismatchException;
    Page<Object> executeSelectEmployee(Pageable pageable, java.lang.Integer SearchID, java.lang.Integer LiveListID) throws QueryParameterMismatchException;
    Page<Object> executeEmployeeListOf_Deptid3(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> execute_ColleagueDetails(Pageable pageable, java.lang.Integer selectedemployeedeptid, java.lang.Integer selectedemployeeid) throws QueryParameterMismatchException;
    Page<Object> executeEmployeeSelectVar(Pageable pageable, java.lang.Integer SelectedEmployee) throws QueryParameterMismatchException;
    Page<Object> executeDepartmentCount(Pageable pageable) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

