/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hr_scaffold.hr.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CountInRegionResponse implements Serializable {

    @ColumnAlias("count(*)")
    private BigInteger count___;

    public BigInteger getCount___() {
        return this.count___;
    }

    public void setCount___(BigInteger count___) {
        this.count___ = count___;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CountInRegionResponse)) return false;
        final CountInRegionResponse countInRegionResponse = (CountInRegionResponse) o;
        return Objects.equals(getCount___(), countInRegionResponse.getCount___());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCount___());
    }
}
