/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hr_scaffold.hr.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class EmployeesByRegionResponse implements Serializable {

    @ColumnAlias("EID")
    private Integer eid;
    @ColumnAlias("FIRSTNAME")
    private String firstname;
    @ColumnAlias("LASTNAME")
    private String lastname;
    @ColumnAlias("STREET")
    private String street;
    @ColumnAlias("CITY")
    private String city;
    @ColumnAlias("STATE")
    private String state;
    @ColumnAlias("ZIP")
    private String zip;
    @ColumnAlias("BIRTHDATE")
    private Date birthdate;
    @ColumnAlias("PICURL")
    private String picurl;
    @ColumnAlias("JOBTITLE")
    private String jobtitle;
    @ColumnAlias("DEPARTMENT")
    private Integer department;
    @ColumnAlias("MANAGER")
    private Integer manager;
    @ColumnAlias("REGION")
    private Integer region;

    public Integer getEid() {
        return this.eid;
    }

    public void setEid(Integer eid) {
        this.eid = eid;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getPicurl() {
        return this.picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    public String getJobtitle() {
        return this.jobtitle;
    }

    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    public Integer getDepartment() {
        return this.department;
    }

    public void setDepartment(Integer department) {
        this.department = department;
    }

    public Integer getManager() {
        return this.manager;
    }

    public void setManager(Integer manager) {
        this.manager = manager;
    }

    public Integer getRegion() {
        return this.region;
    }

    public void setRegion(Integer region) {
        this.region = region;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeesByRegionResponse)) return false;
        final EmployeesByRegionResponse employeesByRegionResponse = (EmployeesByRegionResponse) o;
        return Objects.equals(getEid(), employeesByRegionResponse.getEid()) &&
                Objects.equals(getFirstname(), employeesByRegionResponse.getFirstname()) &&
                Objects.equals(getLastname(), employeesByRegionResponse.getLastname()) &&
                Objects.equals(getStreet(), employeesByRegionResponse.getStreet()) &&
                Objects.equals(getCity(), employeesByRegionResponse.getCity()) &&
                Objects.equals(getState(), employeesByRegionResponse.getState()) &&
                Objects.equals(getZip(), employeesByRegionResponse.getZip()) &&
                Objects.equals(getBirthdate(), employeesByRegionResponse.getBirthdate()) &&
                Objects.equals(getPicurl(), employeesByRegionResponse.getPicurl()) &&
                Objects.equals(getJobtitle(), employeesByRegionResponse.getJobtitle()) &&
                Objects.equals(getDepartment(), employeesByRegionResponse.getDepartment()) &&
                Objects.equals(getManager(), employeesByRegionResponse.getManager()) &&
                Objects.equals(getRegion(), employeesByRegionResponse.getRegion());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEid(),
                getFirstname(),
                getLastname(),
                getStreet(),
                getCity(),
                getState(),
                getZip(),
                getBirthdate(),
                getPicurl(),
                getJobtitle(),
                getDepartment(),
                getManager(),
                getRegion());
    }
}
