/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hr_scaffold.hr.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetRegionResponse implements Serializable {

    @ColumnAlias("region")
    private Integer region;

    public Integer getRegion() {
        return this.region;
    }

    public void setRegion(Integer region) {
        this.region = region;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetRegionResponse)) return false;
        final GetRegionResponse getRegionResponse = (GetRegionResponse) o;
        return Objects.equals(getRegion(), getRegionResponse.getRegion());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRegion());
    }
}
