/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hr_scaffold.hr;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Employees generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Employees`")
public class Employees implements Serializable {

    private Integer eid;
    private String firstname;
    private String lastname;
    private String street;
    private String city;
    private String state;
    private String zip;
    private Date birthdate;
    private String picurl;
    private String jobtitle;
    private Integer department;
    private int manager;
    private Integer region;
    private Integer status;
    private Department departmentByDepartment;
    private Regions regions;
    private EmployeeStatus employeeStatus;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`EID`", nullable = false, scale = 0, precision = 10)
    public Integer getEid() {
        return this.eid;
    }

    public void setEid(Integer eid) {
        this.eid = eid;
    }

    @Column(name = "`FIRSTNAME`", nullable = true, length = 255)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column(name = "`LASTNAME`", nullable = true, length = 255)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "`STREET`", nullable = true, length = 255)
    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    @Column(name = "`CITY`", nullable = true, length = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "`STATE`", nullable = true, length = 255)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "`ZIP`", nullable = true, length = 255)
    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    @Column(name = "`BIRTHDATE`", nullable = true)
    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    @Column(name = "`PICURL`", nullable = true, length = 255)
    public String getPicurl() {
        return this.picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    @Column(name = "`JOBTITLE`", nullable = true, length = 255)
    public String getJobtitle() {
        return this.jobtitle;
    }

    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    @Column(name = "`DEPARTMENT`", nullable = true, scale = 0, precision = 10)
    public Integer getDepartment() {
        return this.department;
    }

    public void setDepartment(Integer department) {
        this.department = department;
    }

    @Column(name = "`MANAGER`", nullable = false, scale = 0, precision = 10)
    public int getManager() {
        return this.manager;
    }

    public void setManager(int manager) {
        this.manager = manager;
    }

    @Column(name = "`REGION`", nullable = true, scale = 0, precision = 10)
    public Integer getRegion() {
        return this.region;
    }

    public void setRegion(Integer region) {
        this.region = region;
    }

    @Column(name = "`STATUS`", nullable = true, scale = 0, precision = 10)
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`DEPARTMENT`", referencedColumnName = "`DEPID`", insertable = false, updatable = false)
    public Department getDepartmentByDepartment() {
        return this.departmentByDepartment;
    }

    public void setDepartmentByDepartment(Department departmentByDepartment) {
        if(departmentByDepartment != null) {
            this.department = departmentByDepartment.getDepid();
        }

        this.departmentByDepartment = departmentByDepartment;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`REGION`", referencedColumnName = "`REGIONID`", insertable = false, updatable = false)
    public Regions getRegions() {
        return this.regions;
    }

    public void setRegions(Regions regions) {
        if(regions != null) {
            this.region = regions.getRegionid();
        }

        this.regions = regions;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`STATUS`", referencedColumnName = "`STATUSID`", insertable = false, updatable = false)
    public EmployeeStatus getEmployeeStatus() {
        return this.employeeStatus;
    }

    public void setEmployeeStatus(EmployeeStatus employeeStatus) {
        if(employeeStatus != null) {
            this.status = employeeStatus.getStatusid();
        }

        this.employeeStatus = employeeStatus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Employees)) return false;
        final Employees employees = (Employees) o;
        return Objects.equals(getEid(), employees.getEid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEid());
    }
}

