/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hr_scaffold.hr;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * Interviews generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Interviews`")
public class Interviews implements Serializable {

    private Integer id;
    @Type(type = "DateTime")
    private LocalDateTime date;
    private Integer candidate;
    private Candidates candidates;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`DATE`", nullable = true)
    public LocalDateTime getDate() {
        return this.date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    @Column(name = "`CANDIDATE`", nullable = true, scale = 0, precision = 10)
    public Integer getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Integer candidate) {
        this.candidate = candidate;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`CANDIDATE`", referencedColumnName = "`ID`", insertable = false, updatable = false)
    public Candidates getCandidates() {
        return this.candidates;
    }

    public void setCandidates(Candidates candidates) {
        if(candidates != null) {
            this.candidate = candidates.getId();
        }

        this.candidates = candidates;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Interviews)) return false;
        final Interviews interviews = (Interviews) o;
        return Objects.equals(getId(), interviews.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

